import os
import sys
import subprocess
from typing import List, Dict, Any

# Ensure we can import src modules
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from src.common.utils import create_mcp_server, setup_logging, tool_error_handler

# Modül 8: Otonom Proje Mimarı (Autonomous Architect)
# Bu sunucu LLM'e uçtan uca dosya yapısı oluşturma ve hata ayıklama yetkisi verir.
setup_logging()
mcp = create_mcp_server("Proje Mimarı Sunucusu")

@mcp.tool()
@tool_error_handler
def generate_boilerplate(project_name: str, files: List[str]) -> str:
    """
    Belirtilen proje için gerekli dosya yapısını ve dizinleri oluşturur.
    Örnek: project_name='my_app', files=['requirements.txt', 'src/main.py']
    """
    base_path = os.path.join(os.getcwd(), project_name)
    os.makedirs(base_path, exist_ok=True)
    
    results = []
    for f in files:
        file_path = os.path.join(base_path, f)
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        if not os.path.exists(file_path):
            with open(file_path, "w") as f_out:
                f_out.write(f"# Auto-generated by MCP Architect: {f}\n")
            results.append(f"OLUŞTURULDU: {f}")
        else:
            results.append(f"ATLÖANDI (Zaten Mevcut): {f}")
            
    return "\n".join(results)

@mcp.tool()
@tool_error_handler
def run_ci_debug_loop(command: str, working_dir: str) -> Dict[str, Any]:
    """
    Belirtilen komutu (test veya build) bir dizinde çalıştırır ve 
    hatayı yakalar. Ajan bu hatayı okuyup kodu düzeltebilir.
    """
    try:
        process = subprocess.run(
            command, 
            shell=True, 
            cwd=os.path.join(os.getcwd(), working_dir),
            capture_output=True, 
            text=True, 
            timeout=30
        )
        
        return {
            "exit_code": process.returncode,
            "stdout": process.stdout,
            "stderr": process.stderr,
            "status": "success" if process.returncode == 0 else "failed"
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

if __name__ == "__main__":
    mcp.run()
